---
title: "Data Collection"
bibliography: ../../assets/references.bib
output: html_document
---

# Overview

To collect online texts from individuals with varying political leanings, this project utilized the Reddit API to scrape text data as test set from Reddit, an American [social news](https://en.wikipedia.org/wiki/Social_news "Social news") [aggregation](https://en.wikipedia.org/wiki/News_aggregator "News aggregator"), [content rating](https://en.wikipedia.org/wiki/Review_site#Rating_site "Review site"), and [forum](https://en.wikipedia.org/wiki/Internet_forum "Internet forum") social network[@reddit2024].

The data collection process began by identifying relevant subreddits (user-created boards organized by topic) through keyword searches. Next, both "hot" and "controversial" submissions(posts) from these subreddits were retrieved, along with their associated comments, to complete the raw data collection. For training set, this projects utilized labelled datasets from Kaggle.

The purpose of this data collection is to obtain a suitable amount and type of text data for subsequent cleaning, analysis, and modeling.
