---
title: "LLM usage log"
---

This page can serve as a "catch-all" for LLM use cases that don’t involve content creation, such as reformatting your own ideas, commenting code that you wrote, or proofreading text, PDF summarization.

LLM tools were used in the following way for the tasks below.

## Brainstorming

-   To create the initial idea, LLM tools were used to brainstorm ideas and provide feedback and refine the project plan
-   To bridge the information gap, LLM tools were used to to recommend available APIs and datasets
-   To enhance the data collection, LLM tools were used to suggest keywords in subreddit (user-created boards organized by topic) searching.

## Writing:

-   Literature search for literature review

-   Text summarization for literature review

-   Reformating the writings to buileted points for better deliverable

-   Summarize key findings from the analysis results and comments I have done

-   Proofread and modify my writing

## Code:

-   Code commenting and explanatory documentation
